---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Автоматический морфологический анализ

Морфологический анализ, как его обычно видят лингвисты, обычно включает в себя несколько вещей:

- определение морфологической формы (например, латинское *mensam* --- [acc.sg]{.smallcaps});
- приведение к начальной форме или основе (*mensam* --- *mensa*, ж. р., первое склонение);
- перевод основы (*mensam* --- 'стол').

В зависимости от целей люди делают акцент на разные аспекты морфологического анализа. Для многих NLP задач полезным является приведение к начальной форме, лингвистический корпусной анализ практически невозможен без заранее определенных морфологических форм, и все три необходимы для представления языкового материала в научной работе. Также стоит помнить, что для разных целей могут быть важны разные категории: например, для согласования может быть важна несловоизменительная для существительных (чаще всего) категория рода.

## Приведение к основе (stemming)

Достаточно широкое применение в ранюю эпоху NLP получили методы, которые позволяют привести словоформы к основе или квазиоснове. Эта процедура помогала уменьшить разнообразие форм в тексте, что облегчало поиск и извлечение информации.


[@porter80]

[@singh17]

## Нейросети

Обычно, если много данных, люди используют нейросети. Для морфологического анализа русского языка их использовали в следующих работах [@arefyev18; @sorokin18; @bolshakova19a; @bolshakova19b; @bolshakova20; @garipov23]. Используются разные архитектуры:

- cвёрточные нейронные сеть (convolutional neural network, CNN);
- деревья решения с градиентным бустингом (decision trees with gradient boosting);
- двунаправленная длинная цепь элементов краткосрочной памяти (Biderectional long short-term memory network, Bi-LSTM);
- и другие.

Другой важный проект, который можно упомянуть в этом разделе: [UDPipe](https://ufal.mff.cuni.cz/udpipe/2) --- проект, основанный на размечанных в формате [Universal Dependencies трибанках](https://universaldependencies.org/) большого количества языков  [@straka18]. Отметим, что их задача амбициознее: они строят модель, совмещающая морфологический парсер и синтаксический парсер дерева зависимостей. Внутри: длинная цепь элементов краткосрочной памяти (LSTM), которая работает на основе векторного представления слов.

## Морфологические трансдьюссеры

### Конечные автоматы

Теория автоматов --- это дисциплина на стыке математики и компьютерных наук, которая появилась в XX веке. Первые конечных автоматов были предложены в работах [@mealy55; @moore56].

```{r}
#| eval: false
#| echo: false

library(DiagrammeR)
grViz('
  digraph G { rankdir="LR"
  node [fontname="Brill",shape=circle,fontsize=14,fixedsize=true]
  edge [fontname="Brill",fontsize=18]
  0 [label="0"];
  1 [label="1"];
  0 -> 1 [label="вверх"];
  0 -> 0 [label="вниз"];
  1 -> 1 [label="вверх"];
  1 -> 0 [label="вниз"];
}')
```



