# Моделирование языковых явлений

## Амбификсы

::: {.callout-note}

###### Задание 04_01

Смоделируйте при помощи `lexd` и `twol` поведение литовского возвратного суффикса -*si*, который занимает позицию перед корнем, если к корню присоединяется любой префикс.

| перевод       | root-inf-rfl | neg-rfl-root-inf |
|---------------|--------------|------------------|
| учиться       | moky-ti-s    | ne-si-moky-ti    |
| радоваться    | džiaug-ti-s  | ne-si-džiaug-ti  |
| осматриваться | žvalgy-ti-s  | ne-si-žvalgy-ti  |
| гордиться     | didžiuo-ti-s | ne-si-didžiuo-ti |
| смеяться      | juok-ti-s    | ne-si-juok-ti    |

:::

## Кабардинское глагольное согласование

::: {.callout-note}

###### Задание 04_02

Мы составили на основе [@kumakhov2006: 169--179] (и с помощью Ю. А. Ландера) фрагмент парадигмы глагола 'идти'[^comitative] в кабардино-черкесском языке (абхазо-адыгские, адыгские). В таблице приводятся поверхностная и глубинные формы. Смоделируйте приведенные формы, используя `lexd` и `twol`. Графема *у* обозначает в данном примере лабиализацию [ʷ] или комбинацию губного аппроксиманта и *ы* [wə]. При моделировании не следует соединять в одной форме префикс дериктива `<dir>` и аппликативов (`<com>`, `<ben>`, `<mal>`). В кабардино-черкесском языке это возможно, но требует дополнительной морфонологии. Алфавит: `а б в д з к н о п с т у ф х щ ъ ы э I`.

```{r}
readr::read_csv("data/04_kabardian_verb.csv") |> 
  DT::datatable(rownames = FALSE, 
                filter = 'top', 
                options = list(pageLength = 70, 
                               autoWidth = TRUE, 
                               info = FALSE,
                               dom = 'fBtp',
                               paginate = FALSE))
```

[^comitative]: Стоит иметь ввиду, что комитативные формы от данного глагола чаще употребляются не в буквальном значении, а в значении "выйти замуж".

:::