project:
  type: book
  output-dir: docs

book:
  title: "Конечные автоматы в морфологическом анализе 2024/2025"
  author: 
  - name: Т. Б. Казакова
  - name: Г. А. Мороз
  repo-url: https://github.com/agricolamz/2025_morphological_transducers/
  chapters:
    - index.qmd
    - 01_introduction_to_transducers.qmd
    - 02_introduction_to_lexd.qmd
    - 03_phonolocial_rules.qmd
    - references.qmd

callout-appearance: simple
callout-icon: false
bibliography: references.bib
language: custom.yml

format:
  html:
    theme: cosmo
    lang: ru
