# Введение {.unnumbered}

Данные материалы являются конспектом курса Т. Б. Казаковой и Г. А. Мороза ‘Конечные автоматы в морфологическом анализе’ 2024--2025. Данный курс предоставляет углубленное изучение применения конечных автоматов в морфологическом анализе. Конечные автоматы используются для моделирования морфологии языков, особенно малоресурсных. Курс охватывает основные этапы создания морфологического анализатора в системе `lexd` и `twol`, проверку его на корпусах, взвешивание трансдьюсера для дизамбигуации. В качестве иллюстративного материала будут использоваться лингвистические задачи и реальные примеры из практики преподавателей. В нашем курсе мы стараемся предложить стратегии компьютерного правилого моделирвания морфологических и морфонологически проблем, стараясь охватить явления интересные с точки зрения теоретической лингвистики.

В курсе будет 6 домашних заданий и экзамен. Все домашние задания имеют одинаковый вес. Экзамен весит 0.4. За курс предусмотрен автомат, если студента устраивает накопленная оценка.

## Список использованных программ {.unnumbered}

```{{shell}}
lexd -V
```

```{python}
!lexd -V
```

```{{shell}}
hfst-twolc -V
```

```{python}
!hfst-twolc -V
```

```{{shell}}
cg3 -V
```

```{python}
!cg3 -V
```

```{{shell}}
git -v
```

```{python}
!git -v
```


## Домашние задания

- [Ссылка](https://classroom.github.com/a/xJfSNmqQ) на первое домашнее задание. Дедлайн: 27 февраля 23:59.
- [Ссылка](https://classroom.github.com/a/erYsHdXt) на второе домашнее задание. Дедлайн: 2 апреля 23:59.
- Ссылка на третье домашнее задание. Дедлайн: 22 мая 23:59.
- Ссылка на четвертое домашнее задание. Дедлайн: 5 июня 23:59.
- Ссылка на четвертое домашнее задание. Дедлайн: 19 июня 23:59.